### PR TITLE
Python3 Support (fixes #4)

### LINKED ISSUE #4: Python 3 support
Would it be possible to support both Python 2 & 3 for this library? I've started a [Python 3 fork](https://github.com/joehand/datpy/tree/python-3) that should support both.

I'll send a PR when it is ready. I wanted to put it in an issue in case anyone else was looking. The fork works for regular usage but doesn't pass all the tests.

Right now the pandas tests are failing in both 2 & 3, everything else passes. I *think* there may be an issue with the `key` storage for dataframes, but I'll open another issue once I figure that out. 

Thanks!

### PR DESCRIPTION
**Pull request by joehand**
Fixes errors in Python 3 (issue #4). The main issue is `stdout` and `stdin` are byte strings, not regular strings. We need to encode before passing to stdin and decode after getting data from stdout. 

All tests pass in Python 2.

***Pickle Test Failing in Python 3***: Unfortunately, things are a bit more complicated w/ Python 3 and reading the pickle file. We can't decode the stdout byte string because it is a pickle file, so we get a `UnicodeDecodeError`. To fix that, we'd have to add this into `stream_out`:
```python
try:
  line = line.decode()
except UnicodeDecodeError:
  line = pickle.loads(line)
  parse = True # avoid creating string later, since we want object
```
Or potentially create a separate read function for pickle files. Neither of these seem like good solutions though. So, not quite sure what to do there and open to suggestions.

### CODE REVIEW

**Comment by karissa** [comment]
@joehand thanks for the PR. I think it'd be good to have a separate read function for pickle files. We actually used to have that but upon updating to beta, I removed it

**Comment by karissa** [comment]
merged, mostly. if you'd like to make another PR for the pickle tests, that'd be awesome!

**Comment by karissa** [comment]
@joehand I actually just committed your suggested code into stream_out because it will be easier for users and I don't really see any immediate drawbacks. Thoughts?

**Comment by joehand** [comment]
@karissa cool! My only hesitation was if the `UnicodeDecodeError` caught other things. I couldn't think of anything but there is probably some bug out there it will catch unintentionally. I think it's fine there for now.

The code as-is had a few issues passing both tests in Python2/3. In the Python 2 version of the test we get back something that needs to go through `pickle.loads()` but not in Python 3 (since it hits the error). I committed a few updates to pass all the tests, I hope that is okay!

We also needed the `parse=True` bit since the `line` becomes a dict after going through `pickle.loads`. Without it, there is an error when trying to `''.join(res)`.

**Comment by karissa** [comment]
Ah yeah, good point @joehand , that's right. Thanks for adding that

**Pull request closed without merging**
