### PR TITLE
Update tests & download function for python 3

### PR DESCRIPTION
**Pull request by joehand**
Python 3 support! 

2 and 3 tests are passing but there are still a few things I am confused about. Seems like there was a change in how dat deals with the main directory between 8.0.3 and 8.0.7. In `dat.download` right now, path is being used a bit inconsistently (but still working, which is the confusing part): 

Line 72 is currently:

``` python
return self.download(link, path)
```

Seems like it should be:

``` python
return self.download(link, path=path)
```

The same issue appears in the tests. Happy to look through it later, first I need to understand how the newest version of dat is dealing with directories (and make ☕️).

I also updated the readme with more consistent test commands across both versions (using `python -m 'nose'` instead of the global nosetests module, where it is harder to tell python version). Let me know if these tests break how you were running tests.

### CODE REVIEW

**Comment by karissa** [comment]
Awesome! Yes, the way dat deals with directories did change, good catch.

Is it just assuming the second argument is for the `path`, even without the keyword arg? It probably should be made explicit, since it is optional afterall.

**Comment by joehand** [comment]
@karissa yes, I had no idea you could do that in python! You can pass keyword/positional arguments as either: 

```python
def remainder(number, divisor):
    return number % divisor

# All the same
remainder(20, 7)
remainder(20, divisor=7)
remainder(number=20, divisor=7)
remainder(divisor=7, number=20)
```

**Comment by joehand** [comment]
It looks like in dat CLI if the download path doesn't exist, it fails. But datpy it works only if the path has one new directory (two or more new subdirs fails), e.g. 

```python
mydat.download(link, '/Users/joe/Desktop/several/new/dirs/')
```


Creating new directories seems like a good thing - but what should we do if the path has more than one new directory? Right now it just throws a OS FileNotFoundError.

**Comment by maxogden** [comment]
joe hand for president

**Comment by karissa** [comment]
@joehand my first inclination is that this should actually be fixed at the dat level

**Comment by karissa** [comment]
@joehand I think we can merge this for now and open that subdir bug as an issue

**Comment by joehand** [comment]
@karissa sounds good. I'll open those issues.

**Pull request merged**
